name: Build Apps

on:
  workflow_dispatch:
  push:
    branches: [ "polywav trimmer" ]
  pull_request:
    branches: [ "polywav trimmer" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Package app
        run: npm run electron:dist -- --publish=never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-release
          path: release/**
